/**
 * PrivacyPilot - HTML Snippet Generators
 * Generates embed codes, HTML downloads, and cookie consent banner code
 */

const Templates = {

  /**
   * Generate a full HTML document for download
   */
  generateFullHTML(title, bodyContent, lang) {
    return `<!DOCTYPE html>
<html lang="${lang || 'zh-CN'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Microsoft YaHei', Georgia, serif;
      line-height: 1.8;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #fff;
    }
    h1 {
      font-size: 1.8rem;
      color: #1a1a2e;
      margin-bottom: 24px;
      border-bottom: 2px solid #6c5ce7;
      padding-bottom: 12px;
    }
    h2 {
      font-size: 1.3rem;
      color: #2d2d5e;
      margin-top: 28px;
      margin-bottom: 12px;
    }
    h3 {
      font-size: 1.1rem;
      color: #3d3d6e;
      margin-top: 20px;
      margin-bottom: 8px;
    }
    p {
      margin-bottom: 12px;
    }
    ul, ol {
      margin: 8px 0 16px 24px;
    }
    li {
      margin-bottom: 6px;
    }
    .effective-date {
      color: #666;
      font-style: italic;
    }
    .legal-disclaimer {
      background: #f8f9fa;
      border-left: 4px solid #6c5ce7;
      padding: 16px;
      margin-top: 24px;
      font-size: 0.85rem;
      color: #666;
      border-radius: 0 8px 8px 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 12px 0;
    }
    th, td {
      padding: 8px;
      text-align: left;
      border: 1px solid #ddd;
    }
    th {
      background: #f0f0f5;
    }
    a {
      color: #6c5ce7;
    }
    @media print {
      body { padding: 20px; }
    }
  </style>
</head>
<body>
${bodyContent}
</body>
</html>`;
  },

  /**
   * Generate cookie consent banner embed code
   */
  generateCookieBanner(config) {
    const {
      bgColor = '#1a1a2e',
      textColor = '#ffffff',
      btnColor = '#6c5ce7',
      btnTextColor = '#ffffff',
      position = 'bottom',
      style = 'bar',
      lang = 'zh'
    } = config;

    const isZh = lang === 'zh';
    const positionCSS = position === 'top'
      ? 'top: 0; border-bottom: 1px solid rgba(255,255,255,0.1);'
      : 'bottom: 0; border-top: 1px solid rgba(255,255,255,0.1);';

    const styleCSS = style === 'floating'
      ? 'left: 20px; right: 20px; max-width: 600px; margin: auto; border-radius: 12px;'
      : style === 'modal'
        ? 'top: 50%; left: 50%; transform: translate(-50%, -50%); max-width: 500px; border-radius: 16px; box-shadow: 0 20px 60px rgba(0,0,0,0.5);'
        : 'left: 0; right: 0;';

    const message = isZh
      ? '我们使用 Cookie 来提升您的体验。继续使用本网站即表示您同意我们的 Cookie 政策。'
      : 'We use cookies to enhance your experience. By continuing to visit this site you agree to our use of cookies.';
    const acceptText = isZh ? '接受' : 'Accept';
    const manageText = isZh ? '管理偏好' : 'Manage Preferences';

    return `<!-- Cookie Consent Banner by PrivacyPilot -->
<div id="cookie-consent-banner" style="display:none; position:fixed; ${positionCSS} ${styleCSS} background-color:${bgColor}; color:${textColor}; padding:20px 24px; z-index:99999; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:14px; line-height:1.5;">
  <div style="display:flex; flex-wrap:wrap; align-items:center; gap:16px; justify-content:space-between;">
    <p style="margin:0; flex:1; min-width:200px;">${message}</p>
    <div style="display:flex; gap:8px; flex-wrap:wrap;">
      <button id="cookie-manage-btn" onclick="document.getElementById('cookie-consent-banner').style.display='none'" style="background:transparent; border:1px solid ${textColor}; color:${textColor}; padding:8px 16px; border-radius:6px; cursor:pointer; font-size:13px;">${manageText}</button>
      <button id="cookie-accept-btn" onclick="document.getElementById('cookie-consent-banner').style.display='none'; document.cookie='cookie_consent=true; path=/; max-age=31536000';" style="background-color:${btnColor}; color:${btnTextColor}; border:none; padding:8px 20px; border-radius:6px; cursor:pointer; font-size:13px; font-weight:600;">${acceptText}</button>
    </div>
  </div>
</div>
<script>
(function(){
  if(!document.cookie.includes('cookie_consent=true')){
    document.getElementById('cookie-consent-banner').style.display='block';
  }
})();
</script>
<!-- End Cookie Consent Banner -->`;
  },

  /**
   * Generate the "embed on your website" snippet
   */
  generatePageEmbedSnippet(title, content) {
    return `<!-- ${title} - Generated by PrivacyPilot -->
<style>
  .pp-policy-container {
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.8;
    color: #333;
  }
  .pp-policy-container h1 {
    font-size: 1.8rem;
    color: #1a1a2e;
    margin-bottom: 24px;
    border-bottom: 2px solid #6c5ce7;
    padding-bottom: 12px;
  }
  .pp-policy-container h2 {
    font-size: 1.3rem;
    color: #2d2d5e;
    margin-top: 28px;
    margin-bottom: 12px;
  }
  .pp-policy-container p { margin-bottom: 12px; }
  .pp-policy-container ul { margin: 8px 0 16px 24px; }
  .pp-policy-container li { margin-bottom: 6px; }
  .pp-policy-container .legal-disclaimer {
    background: #f8f9fa;
    border-left: 4px solid #6c5ce7;
    padding: 16px;
    margin-top: 24px;
    font-size: 0.85rem;
    color: #666;
    border-radius: 0 8px 8px 0;
  }
  .pp-policy-container .effective-date {
    color: #666;
    font-style: italic;
  }
</style>
<div class="pp-policy-container">
${content}
</div>`;
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = Templates;
}
